# Generated by Django 3.0.2 on 2020-01-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20200119_0631'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='musician',
            table='Musician',
        ),
    ]
