# Generated by Django 3.0.2 on 2020-01-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20200125_0302'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='musician',
            table=None,
        ),
    ]
